# Generated by Django 5.0.4 on 2024-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='name',
            field=models.CharField(default='drink1', max_length=200),
            preserve_default=False,
        ),
    ]
